# Generated by Django 3.1.5 on 2021-03-25 22:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_auto_20210323_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigservice',
            name='dateServics',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 1, 13, 16, 909683)),
        ),
        migrations.AddField(
            model_name='smallservice',
            name='dateServics',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 1, 13, 16, 910703)),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('task', models.CharField(max_length=255)),
                ('table_id', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tracking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
