# Generated by Django 3.1.5 on 2021-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
