# Generated by Django 3.1.5 on 2021-03-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0015_auto_20210327_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbill',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customerbill',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
