# Generated by Django 3.1.5 on 2021-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20210327_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='Condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
